default:
  image: ruby@sha256:39d33ab3b46dbfd84609871cf56364d36ba2d9b12731f6bc2fc04afd5274b9d8
  cache:
    paths:
      - vendor/ruby
  before_script:
    - bundle init
    - bundle config set path vendor/ruby
    - bundle add jekyll --version 4.3.2
    - bundle install

stages:
  - test
  - deploy

test-pages:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - main

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main
